### PR TITLE
Cyrillic in Libertinus Serif Bold Italic

### PR DESCRIPTION
**Pull request by StefanPeev**
Cyrillic in Libertinus Serif Bold Italic

### CODE REVIEW

**Comment by StefanPeev** [comment]
I decided to share my Cyrillic proposal for Libertinus Serif Bold Italic. But what happened was not what I expected. Is it possible to ignore all commitments except Cyrillic in Libertinus Serif Bold Italic?

**Comment by StefanPeev** [comment]
OK!

**Comment by khaledhosny** [comment]
I cleaned up and push to `cyrillic` branch in this repo (I couldn’t push to your fork). You can pull this branch and force push it to yours to update this pull request. Something like:
```
git checkout cyrillic
git fetch git@github.com:libertinus-fonts/libertinus.git cyrillic
git reset --hard FETCH_HEAD
git push -f
```

**Comment by StefanPeev** [comment]
After

git fetch git@github.com:libertinus-fonts/libertinus.git cyrillic

I receive

Fatal: Could note read from remote repository

**Comment by StefanPeev** [comment]
And also:

The authenticity of host 'github.com (192.30.253.113)' can't be established.

**Comment by khaledhosny** [comment]
Try `git fetch https://github.com/libertinus-fonts/libertinus.git cyrillic` instead.

**Comment by StefanPeev** [comment]
Now everything is OK. What is the next step?

**Comment by StefanPeev** [comment]
I wanted to submit only this file - LibertinusSerif-BoldItalic.sfd.
I'll make normalize to the file but how to PR only LibertinusSerif-BoldItalic.sfd?

**Comment by khaledhosny** [comment]
Normally, `make normalize` should not make changes to any other files than the one(s) you edited, if it does then something is broken (it may *process* on all the files the first time you run it, but will make no changes to unchanged files). Any way, you can always selectively commit the file you want and ignore the rest.

**Comment by StefanPeev** [comment]
I fail with make normalize command. Is anywhere step by step instructions?

**Comment by StefanPeev** [comment]
I executed this command only once and on UFO files...

**Comment by khaledhosny** [comment]
The steps are mentioned in the README https://github.com/libertinus-fonts/libertinus#contributing. Basically, you just edit the SFD file, run `make normalize` and then `make check`, if all is good commit the SFD file(s) you changed and the corresponding OTF file(s). The files you didn’t touch should remain unchanged, if not please elaborate more on what changes you are seeing.

**Comment by khaledhosny** [comment]
Please do not change the font encoding. The last commit should be reverted and open the font a fresh keeping the existing font encoding to avoid unnecessary file changes.

**Comment by khaledhosny** [comment]
Fixed and pushed manually, thanks.

**Pull request closed without merging**
