### PR TITLE
Libertinus Math: make the vertical bars match the height of the other delimiters

### LINKED ISSUE #175: Libertinus Math: Adjust the sizes of vertical bars with respect to other delimiters
The vertical bars have different heights compared to {}, (), []. This may look odd as the following example shows:

	\documentclass{article}
	
	\usepackage{unicode-math}
	\setmathfont{Libertinus Math}
	
	\begin{document}
		\( \{ x \in \mathbb{R} : 1 < \lvert x \rvert \} \)
	\end{document}

screenshot from 2018-05-07 10-54-20

### PR DESCRIPTION
**Pull request by jco2**
This fixes #175 .

### CODE REVIEW

**Comment by khaledhosny** [comment]
> 135,688 additions, 122,751 deletions

Something is broken here, resizing the bar glyph shouldn’t cause all these changes. GitHub won’t even show me the actual diff.

**Comment by khaledhosny** [comment]
Looks like you opened the OTF file, then saved it over the SFD file. You should open and edit the SFD file instead, build it with `make` and run `make normalize` and `make check` before committing your changes.

**Comment by khaledhosny** [comment]
To rebase cleanly, do:

```
git pull --rebase
```

then, since I changed the normalizer,:
```
make normalize
make
git commit -a --amend
git push -f
```

**Comment by jco2** [comment]
Thank you Khaled ! Now it should be ready to be merged :smiley:

**Comment by jco2** [comment]
@khaledhosny Is it ok now ?

**Pull request closed without merging**
