### PR TITLE
Resize some math glyphs

### PR DESCRIPTION
**Pull request by jco2**
I'm resizing glyphs in the math font (see #63).

### CODE REVIEW

**Comment by khaledhosny** [comment]
That last commit is modifies too many lines, please rebase it away. Lets see what glyphs are causing the issue and manually fix them. Automatic fixing almost always breaks things.

To find which glyph is causing the issue, open the generated OTF file, run “Find problems” dialog and select “Intersecting Paths” from the Paths tab.

**Comment by jco2** [comment]
So I've located the glyphs which cause the issue: they have some overlapping glyphs in them such as /uni226F or /uni2271. How can we fix this ?

**Comment by khaledhosny** [comment]
Looks like your new `greater` glyph has the wrong path direction (did you copy the `less` glyph and flipped it?). Element → Correct direction should fix it.

**Comment by khaledhosny** [comment]
Note also that, the mean reason I didn’t do the scaling tell now is that many of these operators are uses as references in other glyphs, and scaling them will break the other glyphs and you will need to check all the glyphs that reference them one by one (I don’t know of any easy way to find all the glyphs that has a given references, you will probably need to script it and assign such glyphs a certain color and review them).

**Comment by jco2** [comment]
Yes, this was the problem. I plan to add more weight to the math operators just like the \in symbol to better match the font.
I wonder how to make a glyph the mirror of the other: like the < glyph can be edited and the glyph > gets the changes too.

**Comment by jco2** [comment]
Thanks ! What do you think of the changes so far ?
I think math symbols shouldn't have rounded corners, especially considering some glyphs get a mixture of both rounded and not rounded corners.

**Comment by khaledhosny** [comment]
Sorry, I’m a bit busy currently, will check it later.

**Comment by khaledhosny** [comment]
I’m split about the rounded corners, part of me wants to keep it as it can be seen as part of the font overall identity, and part of me finds it a bit weird.

**Comment by alerque** [comment]
I'm sorry just an observer here as I rarely use the math font, but can I just say that "font independent" doesn't really make any sense to me? Why purposefully make any part of a font exactly like some other font? Why wouldn't some elements of character come through in math symbols the same way they do in other symbols? I wouldn't expect this at all and indeed would expect some character to come through. I would expect formulas set in _Libertinus Math_ to feel different than ones set in _STIX Math_ or anything else. If you like the glyphs from another font so much why not use that font instead?

**Comment by jco2** [comment]
Actually I expect some non alphabetical math glyphs to look in a certain way leaving little room for variation. This is why I think some non alphabetical math glyphs can fit any font provided they are modified to match the weight and style of the font. That’s what I currently do and I’m satisfied with the results.

**Comment by khaledhosny** [comment]
Sorry for the delay. I generally like the changes, thanks! I think you missed ÷ and few + signs, also the dots on signs like ∓ and ∔. Also signs like ⪯ are now partially resized and look a bit odd.

**Comment by jco2** [comment]
Thank you for reviewing my changes. Unfortunately I'm no longer interested in contributing since I've settled in an other font and I have other priorities. Thanks again for your help with this stuff ! Keep it up this is a really cool project.

**Comment by khaledhosny** [comment]
OK.

**Pull request closed without merging**
