### PR TITLE
Documentation for OpenType features, Libertinus Serif

### PR DESCRIPTION
**Pull request by gyuris**
Reaction on #173.

### CODE REVIEW

**Comment by nsemrau** [comment]
There seems to be a miniscule typo in the `-ccmp` feature: "Shulfächer" should be "Schulfächer" to be orthographically correct German. :)

**Comment by khaledhosny** [comment]
> 1. ss07: It doesn't works for me. 

It works on capital Eng Ŋ.

> 2. fina: σ→ς doesn't works for me.

This feature should be dropped; `fina` is to be only used for Arabic and similar scripts and most layout engines will not apply it to other scripts. In case of Greek, the two variants are encoded and should not be handled by layout features at all.

> 3. mkmk: I don't understand this feature.

This handles combining marks over other combining marks over other combining marks, e.g. x̆́.

> 4. aalt: Hm... Linux Libertine O works for me, but Libertinus doesn't.

I dropped that feature, it is rather useless IMO.

> 5. I can't reproduce CO₄³⁻ (see last rows in libertinus-sample.odt) with OpenType features...

I dropped the kerning here because it was non-standard, superscript and subscript modifier letters are phonetic symbols and not to be used in math and chemical formulas, these need specialized layout engines.

**Comment by gyuris** [comment]
Thank you for the answer, Khaled. I will update my document shortly.

**Comment by gyuris** [comment]
OK, @khaledhosny If you accept this documentation, please merge. I think there are no more known feature.

Please, say something about this feature documentation. 
If you want, I can add italic, sans, mono etc samples later.

**Comment by gyuris** [comment]
OK, I'm done.

- File format: [.fodt](https://en.wikipedia.org/wiki/OpenDocument_technical_specification#Document_representation) is my suggestion with [`PrettyPrinting`](https://help.libreoffice.org/Common/XML_File_Formats#XML_file_structure) `true` in LibreOffice. LaTeX is hard to me.
- I upgraded to latest font and changed your suggestions.
- `ccmp` is from [original Libertine documentation](http://libertine-fonts.org/) (Contextual Chaining Substitution). I'm a simple end user. I'm not an OpenType expert. I'm just learning how to use OpenType in LibreOffice.

**Comment by khaledhosny** [comment]
Thanks!

**Comment by KrasnayaPloshchad** [comment]
>5. I can't reproduce CO₄³⁻ (see last rows in libertinus-sample.odt) with OpenType features...
>
> I dropped the kerning here because it was non-standard, superscript and subscript modifier letters are phonetic symbols and not to be used in math and chemical formulas, these need specialized layout engines.

That was a work around for many layout engines, for example, Micrsoft Word doesn’t provide the way to make superscript and subscript placed into one block; HTML and CSS also have no specialized methods to produce that, in Wikipedia the editors have to procuce by means of vertical-align property.

**Comment by KrasnayaPloshchad** [comment]
I suggest add the kerning into ZWJ to make it still available.

**Pull request merged**
